# Generated by Django 4.2.1 on 2023-06-08 18:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("manager", "0003_category_transaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="type",
            field=models.CharField(
                choices=[
                    ("checking", "Checking"),
                    ("savings", "Savings"),
                    ("credit", "Credit"),
                ],
                max_length=20,
            ),
        ),
    ]
